### PR TITLE
Added clojurescript compatiblity

### PR DESCRIPTION
**Pull request by stumitchell**
In progress, adding the pull request so I can get travis working

### CODE REVIEW

**Comment by Malabarba** [comment]
Nice. Thanks for taking the time to do this. 
Let me know when travis stops complaining, and don't worry about the `redundancy-check` above.

**Comment by stumitchell** [comment]
Also note I had to remove the tests for 1.5.0 1.6.0 compatibility
Let me know if this is an issue
I think it is important to share tests but we can only do that with reader conditionals which are only available in 1.7.0

**Comment by stumitchell** [comment]
BTW travis has stopped complaining

**Comment by Malabarba** [comment]
Awesome! Thanks again for this.
Sorry for leaving this for so long, I hadn't noticed travis was green.

**Comment by stumitchell** [comment]
Any plans to do a clojars release?
I'll just to a private branch in the meantime

**Comment by stumitchell** [comment]
oh for completeness I will do a slight change to `-assoc` I'll put that in here too.

**Comment by Malabarba** [comment]
I was just about to push to clojars
If you have another change, I can hold the release while you make a PR.

**Comment by stumitchell** [comment]
Cool will do it after my meeting here thanks

**Comment by stumitchell** [comment]
just checked and the `-assoc` code already did what it should do. Feel free to release

**Comment by Malabarba** [comment]
Ok. I'll push when I get home.

**Comment by stumitchell** [comment]
Still waiting on the clojars :-( will it be 1.1?
let me know if you will take a while as I can simply depend on a clojars version under my own name.

**Comment by Malabarba** [comment]
Really sorry  about this! I'm undergoing a reallocation, so my schedules and organisation are a mess right now. 
Feel free to push this to your own clojar username. It might take me a few more days to do it myself.

**Comment by Malabarba** [comment]
Ok. I managed to find a free minute and deployed to clojars today.
Version 1.1

**Comment by stumitchell** [comment]
Thanks a lot I can merge it into my work project now.

**Pull request merged**
